return {
  --   "nvim-neotest/neotest",
  --   ft = { "java" },
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "nvim-treesitter/nvim-treesitter",
  --     "atm1020/neotest-jdtls",
  --   },
  --   keys = {
  --     { "<leader>tt", function() require("neotest").summary.toggle() end,              desc = "Test: toggle summary" },
  --     { "<leader>tr", function() require("neotest").run.run() end,                     desc = "Test: run nearest" },
  --     { "<leader>tR", function() require("neotest").run.run(vim.fn.expand("%")) end,   desc = "Test: run file" },
  --     { "<leader>ta", function() require("neotest").run.run({ suite = true }) end,     desc = "Test: run all (suite)" },
  --     { "<leader>to", function() require("neotest").output.open({ enter = true }) end, desc = "Test: open output" },
  --     { "<leader>tO", function() require("neotest").output_panel.toggle() end,         desc = "Test: toggle output panel" },
  --     { "<leader>tS", function() require("neotest").run.stop() end,                    desc = "Test: stop" },
  --   },
  --   config = function()
  --     require("neotest").setup({
  --       adapters = {
  --         require("neotest-jdtls")({
  --           -- You can put adapter opts here later if needed
  --         }),
  --       },
  --       summary = { animated = false },
  --       quickfix = { enabled = false },
  --       output = { open_on_run = false },
  --       diagnostic = { enabled = true },
  --       icons = {
  --         running_animated = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" },
  --         passed           = "",
  --         failed           = "",
  --         running          = "",
  --         skipped          = "",
  --         unknown          = "?",
  --       },
  --     })
  --   end,
}
