# core
set -g default-terminal "tmux-256color"
set -as terminal-features ',tmux-256color:RGB'
set -g mouse on
set -g history-limit 100000
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set -g status-position top
set -g detach-on-destroy off
set -g exit-empty off

# prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# pane navigation
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# window navigation
bind -n M-h previous-window
bind -n M-l next-window

# session navigation
bind -n M-H switch-client -p
bind -n M-L switch-client -n

# pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# pane splitting
bind '|' split-window -v -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"

# pane closing
bind BSpace kill-pane

# copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'Nybkox/tmux-ukiyo'

# theme
set -g @ukiyo-theme "kanagawa/dragon"

# sessionx
set -g @sessionx-bind 'u'
set -g @sessionx-preview-location 'bottom'
set -g @sessionx-preview-ratio '60%'
set -g @sessionx-window-height '60%'
set -g @sessionx-window-width '60%'
set -g @sessionx-layout 'reverse'
set -g @sessionx-pointer "> "

# restore
set -g @continuum-restore 'on'
set -g @resurrect-restore-message 'off'

# tpm init
run '~/.config/tmux/plugins/tpm/tpm'
