exec-once = easyeffects --gapplication-service
exec-once = hyprpaper

# clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

windowrule = match:class vesktop, workspace 5
windowrule = match:class steam, workspace 5
windowrule = match:class spotify, workspace 5
exec-once = vesktop & spotify-launcher & steam

exec-once = hyprctl dispatch workspace 1
