exec-once = easyeffects --gapplication-service

exec-once = hyprctl keyword 'windowrulev2' 'workspace 5, class:^(discord)$'
exec-once = hyprctl keyword 'windowrulev2' 'workspace 5, class:^(Spotify|spotify)$'
exec-once = hyprctl keyword 'windowrulev2' 'workspace 5, class:^(steam)$'
exec-once = discord & spotify-launcher & steam
exec-once = sleep 5 && hyprctl reload

exec-once = hyprctl dispatch workspace 1
