# monitor
monitor=,preferred,auto,1

#environment
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = GTK_THEME,adw-gtk3-dark

# autostart
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = easyeffects --gapplication-service
exec-once = vesktop
exec-once = feishin
exec-once = steam
exec-once = zen-browser
exec-once = emacs
exec = hyprpaper

# window rules
windowrule = workspace special:magic silent, match:class vesktop
windowrule = workspace special:magic silent, match:class feishin
windowrule = workspace special:magic silent, match:class steam
windowrule = workspace 1 silent, match:class zen-browser
windowrule = workspace 2 silent, match:class emacs

# input
input {
	kb_layout = us
	repeat_rate = 50
	repeat_delay = 200
	follow_mouse = 1
	sensitivity = 0.3
	accel_profile = flat
	force_no_accel = true
}

# appearance
general {
	gaps_in = 0
	gaps_out = 0
	border_size = 1
	col.active_border = rgba(888888ff)
	col.inactive_border = rgba(333333ff)
	layout = master
	no_focus_fallback = true
}

animations {
	enabled = false
}

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
	mouse_move_enables_dpms = true
	key_press_enables_dpms = true
	focus_on_activate = false
}

# layout
master {
	orientation = center
	slave_count_for_center_master = 0
	mfact = 0.5
	new_status = slave
	new_on_top = false
}

# binds
$mod = SUPER
$terminal = kitty
$menu = wofi --show drun

## system
bind = $mod, Return, exec, $terminal
bind = $mod, V, exec, $menu
bind = $mod, E, exec, emacs
bind = $mod, C, killactive

## window state
bind = $mod, N, togglefloating
bind = $mod, M, fullscreen
bind = $mod, W, togglespecialworkspace, magic
bind = $mod SHIFT, W, movetoworkspace, special:magic

## focus
bind = $mod, h, movefocus, l
bind = $mod, j, movefocus, d
bind = $mod, k, movefocus, u
bind = $mod, l, movefocus, r

## move windows
bind = $mod SHIFT, h, movewindow, l
bind = $mod SHIFT, j, movewindow, d
bind = $mod SHIFT, k, movewindow, u
bind = $mod SHIFT, l, movewindow, r

# resize windows
binde = $mod ALT, h, resizeactive, -40 0
binde = $mod ALT, j, resizeactive, 0 40
binde = $mod ALT, k, resizeactive, 0 -40
binde = $mod ALT, l, resizeactive, 40 0

## workspaces
bind = $mod, A, workspace, 1
bind = $mod, S, workspace, 2
bind = $mod, D, workspace, 3
bind = $mod, F, workspace, 4
bind = $mod, G, workspace, 5
bind = $mod SHIFT, A, movetoworkspace, 1
bind = $mod SHIFT, S, movetoworkspace, 2
bind = $mod SHIFT, D, movetoworkspace, 3
bind = $mod SHIFT, F, movetoworkspace, 4
bind = $mod SHIFT, G, movetoworkspace, 5

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bindel = $mod, Q, layoutmsg, orientationnext

bind = , Print, exec, grimblast copy area
bind = SHIFT, Print, exec, grimblast copy screen
bind = ALT, Print, exec, grimblast copy active
