source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/autostart.conf

source = ~/.config/hypr/visuals.conf
source = ~/.config/hypr/inputs.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/monitors.conf

# windowrule = suppressevent maximize, class:.*
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

source = ~/.config/hypr/theme.conf
