$m = SUPER

# App execution
bind = $m SHIFT, RETURN, exec, kitty
bind = $m, RETURN, exec, kitty -e tmux new-session -A -s main
bind = $m, C, killactive
bind = $m, V, exec, $menu
bind = $m SHIFT, V, exec, ~/.config/fuzzel/scripts/powermenu
bind = $m, Z, exec, ~/.config/fuzzel/scripts/clipboard
bind = $m, B, exec, ~/.config/fuzzel/scripts/bluetooth

# bind = $m, BackSpace, exit

# Window control
bind = $m, M, fullscreen
bind = $m, N, togglefloating
bind = $m, Y, pseudo
bind = $m, U, togglesplit

# Focus movement
bind = $m, H, movefocus, l
bind = $m, J, movefocus, d
bind = $m, K, movefocus, u
bind = $m, L, movefocus, r
bind = $m, I, exec, hyprctl activewindow -j | jq -e '.floating' \
  && hyprctl dispatch cyclenext tiled \
  || hyprctl dispatch cyclenext floating

# Move windows
bind = $m SHIFT, H, movewindow, l
bind = $m SHIFT, J, movewindow, d
bind = $m SHIFT, K, movewindow, u
bind = $m SHIFT, L, movewindow, r

# Resize
bindel = $m CTRL, H, resizeactive, -100 0
bindel = $m CTRL, J, resizeactive, 0 100
bindel = $m CTRL, K, resizeactive, 0 -100
bindel = $m CTRL, L, resizeactive, 50 0

# Workspace
bind = $m, A, workspace, 1
bind = $m, S, workspace, 2
bind = $m, D, workspace, 3
bind = $m, F, workspace, 4
bind = $m, G, workspace, 5
bind = $m SHIFT, A, movetoworkspace, 1
bind = $m SHIFT, S, movetoworkspace, 2
bind = $m SHIFT, D, movetoworkspace, 3
bind = $m SHIFT, F, movetoworkspace, 4
bind = $m SHIFT, G, movetoworkspace, 5

# Relative workspace
bind = $m, P, workspace, e+1
bind = $m, O, workspace, e-1

# Special workspace
bind = $m, W, togglespecialworkspace, magic
bind = $m SHIFT, W, movetoworkspace, special:magic

# Cycle workspace
bindel = $m, TAB, cyclenext
bindel = $m SHIFT, TAB, cyclenext, prev

# Cycle orientation (master, center, etc)
bindel = $m, Q, layoutmsg, orientationnext

# Mouse binds
bind = $m, mouse_down, workspace, e+1
bind = $m, mouse_up, workspace, e-1
bindm = $m, mouse:272, movewindow
bindm = $m, mouse:273, resizewindow

# Screenshot
bind = , Print, exec, /home/gaaj/scripts/screenshot area
bind = SHIFT, Print, exec, /home/gaaj/scripts/screenshot full

# Monitor
bind = $m, comma, focusmonitor, l
bind = $m, period, focusmonitor, r
bind = $mod SHIFT, comma, movewindow, mon:l
bind = $mod SHIFT, period, movewindow, mon:r

# Sound
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

