general {
    gaps_in = 5
    gaps_out = 5
    border_size = 1

    resize_on_border = false
    allow_tearing = false

    layout = master
    no_focus_fallback = true
}

decoration {
    rounding = 3
    rounding_power = 5

    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = true
        range = 8
        render_power = 2
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 2
        passes = 2
        vibrancy = 0.1
    }
}

animations {
    enabled = yes

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = windows,    1, 4.5, easeOutQuint
    animation = fade,       1, 2.5, quick
    animation = workspaces, 1, 2, almostLinear, fade
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    orientation = center
    slave_count_for_center_master = 0
    mfact = 0.50
    new_status = slave
    new_on_top = false
}

misc {
    disable_hyprland_logo = true
}
