alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias pac='sudo pacman -S'

alias ls='eza --color=always --icons=always'
alias lsa='eza -a --color=always --icons=always'
alias l='eza --long --color=always --icons=always --no-user --no-time --no-permissions --no-filesize'
alias la='eza -a --long --color=always --icons=always --no-user --no-time --no-permissions --no-filesize'
alias ll='eza --long --color=always --icons=always'
alias lla='eza -a --long --color=always --icons=always'
alias lt='eza --tree -L 5 --git-ignore --color=always --icons=always'
alias lta='eza --tree -a -L 5 --git-ignore --color=always --icons=always'
