### Catppuccin
#include themes/Catppuccin-Mocha.conf
#include themes/Catppuccin-Macchiato.conf
#include themes/Catppuccin-Frappe.conf

#include themes/Brogrammer.conf

include themes/Kanagawa.conf
#include themes/Kanagawa-dragon.conf
