# font
font_family         JetBrainsMono Nerd Font
bold_font           JetBrainsMono Nerd Font Bold
italic_font         JetBrainsMono Nerd Font Italic
bold_italic_font    JetBrainsMono Nerd Font Bold Italic
font_size           11.0

# theme
include     themes/gruvbox_dark_hard.conf

# cursor
cursor_shape            block
cursor_blink_interval   0

# scrollback
scrollback_lines    10000

# mouse
mouse_hide_wait     1.0

# appearance
background_opacity      0.9
window_padding_width    2

# bell
enable_audio_bell   no

# performance
repaint_delay       8
input_delay         2
sync_to_monitor     yes

# shell
shell /bin/zsh
shell_integration   enabled
confirm_os_window_close 0
